name: Yusuph
markdown: kramdown
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num"

# GitHub Pages doesn't support jekyll-paginate-v2, yet!
# permalink: /blog/:year/:month/:day/:title
# plugins: [jekyll-paginate-v2]

# pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true